version: "3.9"
services:
  api:
    build: ./warehouse
    ports:
      - "80:80"
    depends_on:
     - database
    restart: always
  database:
    container_name: sql-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pas50rd1"
      ACCEPT_EULA: "Y"
    restart: always
    expose:  
      - 1433  